version: 0.2

phases:
  build:
    commands:
      - ./gradlew wrapper --gradle-version 6.0.1
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
     - './android/app/build/outputs/**/*.apk'
  discard-paths: yes
